Configuration:
  Properties:
    Property:
    - name: "kafka.logs.dir"
      value: "."
    - name: "logPattern"
      value: "[%d] %p %m (%c)%n"
  Appenders:
    Console:
      name: "STDOUT"
      PatternLayout:
        pattern: "${logPattern}"
    RollingFile:
    - name: "KafkaAppender"
      fileName: "${sys:kafka.logs.dir}/server.log"
      filePattern: "${sys:kafka.logs.dir}/server.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
    - name: "StateChangeAppender"
      fileName: "${sys:kafka.logs.dir}/state-change.log"
      filePattern: "${sys:kafka.logs.dir}/stage-change.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
    - name: "RequestAppender"
      fileName: "${sys:kafka.logs.dir}/kafka-request.log"
      filePattern: "${sys:kafka.logs.dir}/kafka-request.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
    - name: "CleanerAppender"
      fileName: "${sys:kafka.logs.dir}/log-cleaner.log"
      filePattern: "${sys:kafka.logs.dir}/log-cleaner.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
    - name: "ControllerAppender"
      fileName: "${sys:kafka.logs.dir}/controller.log"
      filePattern: "${sys:kafka.logs.dir}/controller.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
    - name: "AuthorizerAppender"
      fileName: "${sys:kafka.logs.dir}/kafka-authorizer.log"
      filePattern: "${sys:kafka.logs.dir}/kafka-authorizer.log.%d{yyyy-MM-dd-HH}"
      PatternLayout:
        pattern: "${logPattern}"
      TimeBasedTriggeringPolicy:
        modulate: true
        interval: 1
  Loggers:
    Root:
      level: "INFO"
      AppenderRef:
      - ref: "STDOUT"
      - ref: "KafkaAppender"
    Logger:
    - name: "org.apache.kafka.controller"
      level: "INFO"
      additivity: false
      AppenderRef:
        ref: "ControllerAppender"
    - name: "kafka.log.LogCleaner"
      level: "INFO"
      additivity: false
      AppenderRef:
        ref: "CleanerAppender"
    - name: "org.apache.kafka"
      level: "INFO"
    - name: "kafka.request.logger"
      level: "WARN"
      additivity: false
      AppenderRef:
        ref: "RequestAppender"
    - name: "kafka"
      level: "INFO"
    - name: "kafka.authorizer.logger"
      level: "INFO"
      additivity: false
      AppenderRef:
        ref: "AuthorizerAppender"
    - name: "kafka.network.RequestChannel$"
      level: "WARN"
      additivity: false
      AppenderRef:
        ref: "RequestAppender"
    - name: "state.change.logger"
      level: "INFO"
      additivity: false
      AppenderRef:
        ref: "StateChangeAppender"
