Configuration:
  Properties:
    Property:
    - name: "logPattern"
      value: "[%d] %p %m (%c)%n"
  Appenders:
    Console:
      name: "STDERR"
      target: "SYSTEM_ERR"
      PatternLayout:
        pattern: "${logPattern}"
  Loggers:
    Root:
      level: "WARN"
      AppenderRef:
      - ref: "STDERR"
